- block:
    - name: copy git config template
      copy:
        src: .gitconfig
        dest: "~{{ local_username }}/.gitconfig"
        force: yes
  become: yes
  become_user: "{{ local_username  }}"